email_add= "name:username"
checkout_firstName ="name:firstname"
checkout_lastName ="name:lastname"
company = "name:company"
street= "name:street[0]"
city= "name:city"
state= "name:region_id"
zipcode ="name:postcode"
country = "name:country_id"
phone = "name:telephone"
select_shipping_method = "name:ko_unique_7"
next_btn= "xpath://button[@class='button action continue primary']"
order_btn = "xpath://span[normalize-space()='Place Order']"